version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq/data